version: "3.8"  # optional since v1.27.0
services:
  maven:
    build: maven
    tty: true
    ports:
      - "8082:8080"
    volumes:
      - ../project:/webapp

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    volumes:
#      - ./db/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
